### PR TITLE
feat: Support components filter in pathContents (#825)

### PR DESCRIPTION
**Pull request by JerrySentry**
### Purpose/Motivation
Adds component filtering in pathContents query

### Links to relevant tickets

https://github.com/codecov/engineering-team/issues/825

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by RulaKhaled — APPROVED** [review]
Nice Jerry! 🚀

**Review by RulaKhaled — CHANGES_REQUESTED** [review]
Before we merge this, can you push and test on staging please? 

something i want to confirm is that although commit_report is different than filtered commit report, it still behaves as intended

**Comment by JerrySentry** [comment]
> Before we merge this, can you push and test on staging please?
> 
> something i want to confirm is that although commit_report is different than filtered commit report, it still behaves as intended
@RulaKhaled 
Did some testing with the two components on worker repo, seems fine to me. I was investigating into `FilteredReport` vs `Report` recently, afaik they share the same properties, and in FilteredReport it has an instance of the Report then when we access the properties in the FilteredReport it will do a bunch of flag filtering logic against the store Report instance.

**Comment by RulaKhaled** [comment]
> > Before we merge this, can you push and test on staging please?
> > something i want to confirm is that although commit_report is different than filtered commit report, it still behaves as intended
> 
> @RulaKhaled Did some testing with the two components on worker repo, seems fine to me (I mostly used my local dev setup with better components setup prior to this). I was investigating into `FilteredReport` vs `Report` recently, afaik they share the same properties, and in FilteredReport it has an instance of the Report then when we access the properties in the FilteredReport it will do a bunch of flag filtering logic against the store Report instance.

Sounds good to me!

**Review by RulaKhaled — APPROVED** [review]

**Pull request merged**
